### ISSUE TITLE
Showing thumbnail

### ISSUE THREAD

**Issue by silbang** [daggerhart/taxonomy-term-image#4]
I cant show the thumbnail image. Please help me. 

can you guide me? Thanks!

**Comment by daggerhart** [comment]
It depends on your current context.  What template are you trying to show the image in?

If you're using an archive page, this code should work:

``` php
$term = get_queried_object();

if ( $term->term_image ){
    echo wp_get_attachment_image( $term->term_image, 'thumbnail' );
}
```

**Comment by silbang** [comment]
This is the situation. I have a custom template, and I want to show my custom taxonomy named "Products" and their images. Here is my code:

 $args = array(
    'type'                     => 'post',
    'child_of'                 => 0,
    'parent'                   => 0,
    'orderby'                  => 'name', 
    'order'                    => 'ASC',
    'hide_empty'               => 0,
    'hierarchical'             => 1,
    'taxonomy'                 => 'Products'
    );

 foreach ( get_categories( $args ) as $taxonomy_cat){

```
$get_category = get_queried_object($taxonomy_cat);

echo '<li>' . $taxonomy_cat->name.'</li>';
```

my taxonomy is showing but I don't know how to show the images.

**Comment by daggerhart** [comment]
It should work like this: 

``` php
$args = array(
'type' => 'post',
'child_of' => 0,
'parent' => 0,
'orderby' => 'name',
'order' => 'ASC',
'hide_empty' => 0,
'hierarchical' => 1,
'taxonomy' => 'Products'
);

foreach ( get_categories( $args ) as $taxonomy_cat ) {
  echo '<li>' . 
    wp_get_attachment_image( $taxonomy_cat->term_image, 'thumbnail' ) . 
    $taxonomy_cat->name . 
    '</li>';
}
```

**Comment by silbang** [comment]
An error: Undefined property: stdClass::$term_image

Here is my full code:

<?php 
/**
Template Name: Products
*/
?>
<?php get_header();?>



<?php 
$args = array(
'type' => 'post',
'child_of' => 0, 
'parent' => 0,
'orderby' => 'name',
'order' => 'ASC',
'hide_empty' => 0,
'hierarchical' => 1,
'taxonomy' => 'Products'
);

foreach ( get_categories( $args ) as $taxonomy_cat ) {
  echo '<li>' . 
    wp_get_attachment_image( $taxonomy_cat->term_image, 'thumbnail' ) . 
    $taxonomy_cat->name . 
    '</li>';
?>

<?php
/*

// The Query 
// WP_Query arguments
   $wp_query = new WP_Query( array(
      'post_type'                => 'product',
      'post_status'          => 'publish',
    'orderby'                => 'date'
    ));

```
if( have_posts() ) { 
    while ( $wp_query->have_posts() ) { 
        $wp_query->the_post();



        ?>


        <?php 
        echo '<li>'; 
        the_post_thumbnail(); //for featured image ?>
         <h3><?php the_title();?> </h3>
        <p> <?php the_content(); ?></p>
        <?php echo '</li>';
    }
} 
else {
    echo '<p>Sorry, no posts matched your criteria. </p>';
} 
wp_reset_query();   */
```

?>  

 <script type="text/javascript">
    $(document).ready(function() {
      $('.grid-nav li a').on('click', function(event){
        event.preventDefault();
        $('.grid-container').fadeOut(500, function(){
          $('#' + gridID).fadeIn(500);
        });
        var gridID = $(this).attr("data-id");

```
    $('.grid-nav li a').removeClass("active");
    $(this).addClass("active");
  });
});
</script>

<script type="text/javascript">
$(document).ready(function() {
  $('.grid li a').on('click', function(event){
    event.preventDefault();
    $('.grid-container').fadeOut(500, function(){
      $('#' + gridID).fadeIn(500);
    });
    var gridID = $(this).attr("data-id");

    $('.grid li a').removeClass("active");
    $(this).addClass("active");
  });
});
</script>
```

<?php get_footer();?>

**Comment by silbang** [comment]
or the url of the image.

**Comment by daggerhart** [comment]
Hi silbang,

I found the fix to your problem, turns out get_categories() never fired the get_term hook.  Sorry for the delay.
