### ISSUE TITLE
Use term meta instead of options table

### ISSUE THREAD

**Issue by gonssal** [daggerhart/taxonomy-term-image#9]
I adapted your code to use core's [recently introduced](https://make.wordpress.org/core/2015/10/23/4-4-taxonomy-roundup/) term meta functionality instead of the options table.

Would you consider accepting a pull request or should I just publish a new repo?

Please note that, because I wasn't using the code before term meta was introduced, I haven't written any code to migrate the existing options to term meta.

**Comment by daggerhart** [comment]
Hi gonssal, Thanks for the help!

I'm definitely interested in seeing your project, but I might have done this already. Check out the 2.x branch of this repo and let me know what you think. Any thoughts / improvements are welcome!

**Comment by gonssal** [comment]
Fair enough, didn't see the 2.x branch. Maybe copy the current master to a 1.x branch and set 2.x as master?

I checked out the new code and worked out of the box with the meta I already had set, the code is almost exactly the same as what I did with plus the `upgrade` function. The only thing I'd change is using a closure in the 'init' `add_action`, because while not recommended, WordPress still supports PHP 5.2.

Also, I think at line 107, the conditional should be:
`if ( ! empty( $this->option_name ) && version_compare( $previous_version, $this->version, '<' ) ){`
so we don't perform an unnecessary get_option(). Then the `update_option( 'taxonomy-term-image-version', $this->version );` line should stay in the current conditional.

**Comment by daggerhart** [comment]
That all sounds reasonable to me, thanks for the feedback.  If you want to submit those 2 improvements as pull requests to 2.x, I'm happy to merge.  Alternatively, I don't mind doing it.  Your call

**Comment by daggerhart** [comment]
I've merged 2.x into master, and removed the closure.  After reviewing it further, I didn't change the upgrade conditional because it seems very unlikely that the option_name will be empty considering the constructor sets a default value.   

Thanks again for the help and suggestions.  Let me know if you run across anything else that could be improved.
